# Site settings
title: ov3rk1ll
email: me@ov3rk1ll.dev
url: https://ov3rk1ll.dev
description: "Android, Web and Server development"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: "#000000"
  links: "#515e92"

# Footer settings
footer: ov3rk1ll

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/stephan-gruber-a763ba83/
  - title: github
    url: https://github.com/ov3rk1ll

# Build settings
markdown: kramdown
permalink: pretty
